# Separate compose file to deploy only Cloud based services
version: '3'

services:

  cloud_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  grafana:
    build: ./grafana/
    depends_on:
      - cloud_db
    ports:
      - 3000:3000
