apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    access: direct
    uid: postgres
    url: cloud_db:5432
    user: postgres
    database: postgres
    jsonData:
      sslmode: disable
    secureJsonData:
      password: postgres
